substitutions:
  device_name: Haier Appliance
  device_id: haier_appliance
  uart_id: appliance_port

esphome:
  name: ${device_id}
  comment: ${device_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    
api:
  reboot_timeout: 0s

ota:

web_server:

logger:
  level: DEBUG

uart:
  baud_rate: 9600
  tx_pin: 17
  rx_pin: 16
  id: ${uart_id}

external_components:
  source:
    type: local
    path: ./components
  components: [ haier_wm ]

haier_wm: